### ISSUE TITLE
`@option` doesn't appear to work properly

### ISSUE THREAD

**Issue by marnen** [lsegal/rubydoc.info#90]
Take a look at http://www.rubydoc.info/gems/foundation_form_builder/0.3.1/FoundationFormBuilder/Rails and its corresponding source at https://github.com/marnen/foundation_form_builder/blob/v0.3.1/lib/foundation_form_builder/rails.rb . Notice that the `@option` tags are not being picked up. Help?

**Comment by lsegal** [comment]
The markup isn't correct there. For `@option` tags, the "options" argument name needs to actually exist as a parameter in the method def. Use `@param` for keyword args. See lsegal/yard#729 for more info.

**Comment by marnen** [comment]
OK, that's totally unclear from the docs at http://www.rubydoc.info/gems/yard/file/docs/Tags.md. However, I have difficulty understanding how lsegal/yard#729 applies to my use case (where I don't have `**kwargs`). Do I just use `@param` for each keyword as if it were a regular parameter?

**Comment by lsegal** [comment]
> OK, that's totally unclear from the docs at http://www.rubydoc.info/gems/yard/file/docs/Tags.md. 

Tag documentation currently has no mention of keyword args since it's only recently supported. Patches accepted to add better docs there.

> I have difficulty understanding how lsegal/yard#729 applies to my use case 

The linked issue is a superset of this use case, it discusses both splat kwargs and individual args.

> Do I just use @param for each keyword as if it were a regular parameter?

Yes. They *are* regular parameters from Ruby's point of view of the method declaration. In other words, they exist as local variables in your method scope.

**Comment by marnen** [comment]
Great, thanks. I'll submit a docs patch.

**Comment by marnen** [comment]
Docs patch is at https://github.com/lsegal/yard/pull/838.
